# Generated by Django 2.2.7 on 2019-11-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='service',
            new_name='role',
        ),
    ]
