# Generated by Django 2.2.7 on 2019-12-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191129_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='departement',
            new_name='department',
        ),
    ]
