# Generated by Django 2.2.6 on 2020-01-14 15:50

import analizer.production_models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=128)),
                ('info_grume', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfoGrume, null=True)),
                ('mesure_grume', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.MesureGrume, null=True)),
                ('info_sciage', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfosSciage, null=True)),
                ('causes_rescans', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.CausesRescans, null=True)),
                ('temps_de_cycle', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.TempsDeCycle, null=True)),
                ('infos_cycle_automate', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfosCycleAutomate, null=True)),
                ('cause_interruptions_table', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.CausesInterruptionsTable, null=True)),
                ('cause_interruptions_sciage', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.CausesInterruptionsSciage, null=True)),
                ('info_configuration_ligne', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfoConfigurationLigne, null=True)),
                ('info_temps_de_cycle', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfosTempsDeCycle, null=True)),
                ('info_temps_de_cycle_sciage', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfoTempsDeCycleSciage, null=True)),
            ],
        ),
    ]
