# Generated by Django 2.2.7 on 2019-12-03 13:11

import analizer.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infosciage', djongo.models.fields.ArrayModelField(model_container=analizer.models.DataInfoSciage)),
            ],
        ),
    ]
