# Generated by Django 2.2.7 on 2019-12-02 16:02

import analizer.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grumedata', djongo.models.fields.EmbeddedModelField(model_container=analizer.models.GrumeData, null=True)),
                ('infosciage', djongo.models.fields.ArrayModelField(model_container=analizer.models.DataInfoSciage)),
            ],
        ),
        migrations.CreateModel(
            name='CauseEvenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.TimeField()),
                ('cause', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataInfoSciage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproduits', models.PositiveIntegerField()),
                ('epaisseur', models.PositiveIntegerField()),
                ('largeur', models.PositiveIntegerField()),
                ('longueur', models.PositiveIntegerField()),
                ('info', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrumeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infogrume', djongo.models.fields.EmbeddedModelField(model_container=analizer.models.InfoGrume, null=True)),
                ('mesuregrume', djongo.models.fields.EmbeddedModelField(model_container=analizer.models.MesureGrume, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoGrume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numgrum', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
                ('qualite', models.PositiveIntegerField()),
                ('numcampagne', models.PositiveIntegerField()),
                ('reserve', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MesureGrume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longueurreellemm', models.PositiveIntegerField()),
                ('longueurpourcyclequaismm', models.PositiveIntegerField()),
                ('longueurmarchandemm', models.PositiveIntegerField()),
                ('diametrefinBoutmm', models.PositiveIntegerField()),
                ('diametreGrosBoutmm', models.PositiveIntegerField()),
                ('diametremoyenm', models.PositiveIntegerField()),
                ('diametremilieumm', models.PositiveIntegerField()),
                ('diametrecyclindreinscritmm', models.PositiveIntegerField()),
                ('diametrecubagemm', models.PositiveIntegerField()),
                ('longueurcubagemm', models.PositiveIntegerField()),
                ('cubagereelcm3', models.PositiveIntegerField()),
                ('reserve1', models.PositiveIntegerField()),
                ('reserve2', models.PositiveIntegerField()),
                ('reserve3', models.PositiveIntegerField()),
                ('reserve4', models.PositiveIntegerField()),
            ],
        ),
    ]
