# Generated by Django 2.2.4 on 2019-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoConfigurationLigne',
        ),
        migrations.DeleteModel(
            name='InfosTempsDeCycle',
        ),
    ]
