# Generated by Django 2.2.7 on 2019-12-03 13:27

import analizer.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='grumedata',
            field=djongo.models.fields.EmbeddedModelField(model_container=analizer.models.GrumeData, null=True),
        ),
    ]
