# Generated by Django 2.2.6 on 2020-01-07 08:30

import analizer.production_models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='info_sciage',
            field=djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfosSciage, null=True),
        ),
    ]
