# Generated by Django 2.2.6 on 2019-12-12 13:16

import analizer.production_models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfosSciage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_info_sciage', djongo.models.fields.ArrayModelField(model_container=analizer.production_models.DataInfoSciage)),
            ],
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='grume_data',
        ),
        migrations.AddField(
            model_name='campagne',
            name='info_grume',
            field=djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.InfoGrume, null=True),
        ),
        migrations.AddField(
            model_name='campagne',
            name='mesure_grume',
            field=djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.MesureGrume, null=True),
        ),
    ]
