# Generated by Django 2.2.6 on 2019-12-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0002_auto_20191212_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfosSciage',
        ),
    ]
