# Generated by Django 2.2.6 on 2019-12-10 14:56

import analizer.production_models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0002_auto_20191206_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', djongo.models.fields.EmbeddedModelField(model_container=analizer.production_models.Toto, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
