# Generated by Django 2.2.5 on 2019-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=64)),
                ('service', models.CharField(choices=[('S1', 'Service 1'), ('S2', 'Service 2'), ('S3', (('31', 'Service 3.1'), ('32', 'Service 3.2')))], default='', max_length=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
