# Generated by Django 2.2.7 on 2019-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cible',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
    ]
